###ทำเรียงข้อได้เลยครับข้อมูลของ ข้อ 1 จะใช้อ้างอิงข้อต่อๆไป

###สร้างรถไฟและชื่อ
POST http://localhost:8000/trains/
Content-Type: application/json

[
  {
    "train_id": "1",
    "train_name": "ขบวนรถชานเมือง (Commuter) 303"
  },
  {
    "train_id": "2",
    "train_name": "ขบวนรถด่วนพิเศษ ( Special Express ) 177"
  }  
]


###เพิ่มข้อมูลสถานี

POST http://localhost:8000/stations/
Content-Type: application/json

[
  {
    "station_id": "1",
    "station_name": "กรุงเทพ"
  },
  {
    "station_id": "2",
    "station_name": "สามเสน"
  },
  {
    "station_id": "3",
    "station_name": "ชุมทางบางซื่อ"
  },
  {
    "station_id": "4",
    "station_name": "กรุงเทพอภิวัฒน์"
  },
  {
    "station_id": "5",
    "station_name": "ดอนเมือง"
  },
  {
    "station_id": "6",
    "station_name": "รังสิต"
  },
  {
    "station_id": "7",
    "station_name": "เชียงราก"
  },
  {
    "station_id": "8",
    "station_name": "บางปะอิน"
  },
  {
    "station_id": "9",
    "station_name": "อยุธยา"
  },
  {
    "station_id": "10",
    "station_name": "ชุมทางบ้านภาชี"
  },
  {
    "station_id": "11",
    "station_name": "หนองวิวัฒน์ "
  },
  {
    "station_id": "12",
    "station_name": "ท่าเรือ"
  },
  {
    "station_id": "13",
    "station_name": "บ้านหมอ"
  },
  {
    "station_id": "14",
    "station_name": "หนองโดน"
  },
  {
    "station_id": "15",
    "station_name": "บ้านกลับ"
  },
  {
    "station_id": "16",
    "station_name": "บ้านป่าหวาย"
  },
  {
    "station_id": "17",
    "station_name": "ลพบุรี"
  },
  {
    "station_id": "30",
    "station_name": "เชียงใหม่"
  }
]
###

GET http://localhost:8000/stations/


### เพิ่มข้อมูลเส้นทางเดินรถ
POST http://localhost:8000/routes/
Content-Type: application/json

[
  {
    "route_id": "1",
    "route_name": "กรุงเทพ-ลพบุรี",
    "train_id": "1",
    "startstation_id": "1",
    "endingstation_id": "17",
    "route_date": "20/03/67"
  },
  {
    "route_id": "2",
    "route_name": "กรุงเทพ-เชียงใหม่",
    "train_id": "2",
    "startstation_id": "1",
    "endingstation_id": "18",
    "route_date": "25/03/67"
  }  
]

###

GET  http://localhost:8000/routes/


###เพิ่มข้อมูลจุดหยุดของเที่ยวรถ กรุงเทพ-ลพบุรี
POST http://localhost:8000/stopstations/
Content-Type: application/json

[
  {
    "route_id": "1",
    "station_id": "1",
    "arrival_time": "",
    "departure_time": "04.15"
  },
  {
    "route_id": "1",
    "station_id": "2",
    "arrival_time": "04.26",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "3",
    "arrival_time": "04.33",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "4",
    "arrival_time": "04.34",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "5",
    "arrival_time": "04.58",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "6",
    "arrival_time": "05.08",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "7",
    "arrival_time": "05.15",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "8",
    "arrival_time": "05.35",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "9",
    "arrival_time": "05.48",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "10",
    "arrival_time": "06.15",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "11",
    "arrival_time": "06.25",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "12",
    "arrival_time": "06.34",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "13",
    "arrival_time": "06.41",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "14",
    "arrival_time": "06.47",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "15",
    "arrival_time": "06.53",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "16",
    "arrival_time": "06.59",
    "departure_time": ""
  },
  {
    "route_id": "1",
    "station_id": "17",
    "arrival_time": "07.05",
    "departure_time": ""
  }
]

###
GET  http://localhost:8000/stopstations/

###โจทย์ ข้อ1
### แสดงเส้นทางขบวนรถไฟ พร้อมจุดหยุดและเวลาถึง ของ route_id = 1
GET http://localhost:8000/routestationinfo/1

